latitude_home: "{{ home_latitude }}"
longitude_home: "{{ home_longitude }}"

netatmo_client_id: "{{ netatmo_client_id }}"
netatmo_client_secret: "{{ netatmo_client_secret }}"

philips_hue_bridge_ip: "{{ philips_hue_bridge_ip}}"

traefik_ip: "{{ traefik_docker_ip }}"

home_assistant_url: "https://{{ home_assistant_domain }}"

influxdb_username: "{{ influxdb_home_assistant_username }}"
influxdb_password: "{{ influxdb_home_assistant_password }}"
influxdb_hostname: "{{ influxdb_domain }}"
