apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
  url: https://argocd.lan.juusoleinonen.fi
