###########################
# Security
###########################
ansible_ssh_user: pi
docker_users:
  - "pi"

allowed_network_sources:
  - "{{ iot_vlan_network }}"
  - "{{ main_vlan_network }}"
  - "{{ lan_network }}"
  - "{{ remote_vpn_network }}"

gateway_docker_network: "home-assistant-network"
gateway_docker_network_subnet: "172.20.0.0/16"
gateway_docker_network_gateway: "172.20.0.1"
gateway_user: "home_assistant"
security_allow_http_traffic: true
security_allow_https_traffic: true

host_specific_firewall_rules: []

###########################
# Traefik
###########################
traefik_home_folder: "/home/{{ gateway_user }}/traefik"
traefik_user: "{{ gateway_user }}"

traefik_docker_network: "{{ gateway_docker_network }}"
traefik_docker_network_subnet: "{{ gateway_docker_network_subnet }}"
traefik_docker_network_gateway: "{{ gateway_docker_network_gateway }}"
traefik_docker_ip: "172.20.0.2"

traefik_version: "v3.2.1"
traefik_domain: "{{ vault_traefik_domain }}"

lets_encrypt_use_production: true

###########################
# Zigbee2MQTT
###########################
zigbee2mqtt_home_folder: "/home/{{ gateway_user }}/zigbee2mqtt"
zigbee2mqtt_user: "{{ gateway_user }}"
zigbee2mqtt_domain: "{{ vault_zigbee2mqtt_domain }}"
zigbee2mqtt_docker_network_subnet: "{{ gateway_docker_network_subnet }}"
zigbee2mqtt_docker_network: "{{ gateway_docker_network }}"
zigbee2mqtt_docker_network_gateway: "{{ gateway_docker_network_gateway }}"
zigbee2mqtt_version: "1.41.0"
zigbee2mqtt_network_key: "{{ vault_zigbee2mqtt_network_key }}"

###########################
# BLE2MQTT
###########################
ble2mqtt_home_folder: "/home/{{ gateway_user }}/ble2mqtt"
ble2mqtt_user: "{{ gateway_user }}"
ble2mqtt_version: "edge"
