services:
  influxdb:
    container_name: influxdb
    image: "influxdb:{{ influxdb_version }}"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/influxdb
    environment:
      - TZ=Europe/Helsinki
      - "INFLUXDB_ADMIN_USERNAME={{ influxdb_admin_username }}"
      - "INFLUXDB_ADMIN_PASSWORD={{ influxdb_admin_password }}"
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_AUTH_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`{{ influxdb_domain }}`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=lets-encrypt"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    networks:
      - "{{ influxdb_docker_network }}"
  chronograf:
    container_name: chronograf
    image: "chronograf:{{ chronograf_version }}"
    depends_on:
      - influxdb
    volumes:
      - ./chronograf:/var/lib/chronograf
    environment:
      - TZ=Europe/Helsinki
      - "INFLUXDB_URL=https://{{ influxdb_domain }}"
      - "INFLUXDB_USERNAME={{ influxdb_admin_username }}"
      - "INFLUXDB_PASSWORD={{ influxdb_admin_password }}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.rule=Host(`{{ chronograf_domain }}`)"
      - "traefik.http.routers.chronograf.entrypoints=websecure"
      - "traefik.http.routers.chronograf.tls.certresolver=lets-encrypt"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"
    networks:
      - "{{ influxdb_docker_network }}"
networks:
  "{{ influxdb_docker_network }}":
    external: true
