- name: Ensure grafana user exists
  ansible.builtin.user:
    name: "{{ grafana_user }}"
    comment: Grafana user
    uid: 472
    group: root

- name: Ensure Grafana docker network exists
  community.docker.docker_network:
    name: "{{ grafana_docker_network }}"
    ipam_config:
      - subnet: "{{ grafana_docker_network_subnet }}"
        gateway: "{{ grafana_docker_network_gateway }}"
    state: present
    appends: yes

- name: Ensure Grafana folder exists
  file:
    path: "{{ grafana_home_folder }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: root
    mode: 0755

- name: Ensure Grafana data folder exists
  file:
    path: "{{ grafana_home_folder }}/data"
    state: directory
    owner: "{{ grafana_user }}"
    group: root
    mode: 0755

- name: Ensure Grafana config file is present
  template:
    src: grafana.ini
    dest: "{{ grafana_home_folder }}/grafana.ini"
    group: root
    mode: 0644
    owner: "{{ grafana_user }}"
  notify: restart grafana

- name: Ensure Grafana datasources.yml file is present
  template:
    src: datasources.yml
    dest: "{{ grafana_home_folder }}/datasources.yml"
    group: root
    mode: 0644
    owner: "{{ grafana_user }}"
  notify: restart grafana

- name: Ensure Grafana docker-compose file is present
  template:
    src: docker-compose.yml
    dest: "{{ grafana_home_folder }}/docker-compose.yml"
    group: root
    mode: 0644
    owner: "{{ grafana_user }}"
  notify: restart grafana

- name: Ensure grafana is running
  community.docker.docker_compose:
    project_src: "{{ grafana_home_folder }}"
    state: present