---
roles:
  - name: geerlingguy.pip
    version: "3.0.3"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "7.1.0"
  - name: geerlingguy.nfs
    version: 2.0.0

collections:
  - name: community.general
    version: "8.4.0"
  - name: community.docker
    version: "3.8.1"
  - name: ansible.posix
    version: "1.5.4"
  - name: kubernetes.core
    version: "3.0.1"
  - name: vladgh.samba
    version: "3.3.0"
