---
roles:
  - name: geerlingguy.pip
    version: "2.1.0"
  - name: geerlingguy.docker_arm
    version: "5.0.0"

collections:
  - name: community.general
    version: "5.5.0"
  - name: community.docker
    version: "3.0.2"
