---
roles:
  - name: geerlingguy.pip
    version: "3.0.3"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "7.4.1"
  - name: geerlingguy.nfs
    version: 2.1.0

collections:
  - name: community.general
    version: "9.2.0"
  - name: community.docker
    version: "3.12.1"
  - name: ansible.posix
    version: "1.5.4"
  - name: kubernetes.core
    version: "5.0.0"
  - name: vladgh.samba
    version: "3.4.0"
