---
roles:
  - name: geerlingguy.pip
    version: "3.1.0"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "7.4.7"
  - name: geerlingguy.nfs
    version: 2.1.0

collections:
  - name: community.general
    version: "10.3.1"
  - name: community.docker
    version: "4.5.2"
  - name: ansible.posix
    version: "2.0.0"
  - name: kubernetes.core
    version: "5.2.0"
  - name: vladgh.samba
    version: "3.4.0"
