---
roles:
  - name: geerlingguy.pip
    version: "2.2.0"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "6.1.0"

collections:
  - name: community.general
    version: "7.0.0"
  - name: community.docker
    version: "3.4.5"
  - name: ansible.posix
    version: "1.5.2"
  - name: kubernetes.core
    version: "2.4.0"
