---
roles:
  - name: geerlingguy.pip
    version: "3.1.1"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "7.9.0"
  - name: geerlingguy.nfs
    version: 2.1.1

collections:
  - name: community.general
    version: "12.1.0"
  - name: community.docker
    version: "5.0.4"
  - name: ansible.posix
    version: "2.1.0"
  - name: kubernetes.core
    version: "6.2.0"
  - name: vladgh.samba
    version: "3.5.4"
