---
roles:
  - name: geerlingguy.pip
    version: "2.2.0"
  - name: geerlingguy.docker_arm
    version: "5.0.0"
  - name: geerlingguy.docker
    version: "7.0.1"
  - name: geerlingguy.nfs
    version: 2.0.0

collections:
  - name: community.general
    version: "7.4.0"
  - name: community.docker
    version: "3.4.8"
  - name: ansible.posix
    version: "1.5.4"
  - name: kubernetes.core
    version: "2.4.0"
  - name: vladgh.samba
    version: "3.2.2"
