---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  namespace: influxdb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`influxdb.lan.juusoleinonen.fi`)
      priority: 10
      services:
        - name: influxdb-influxdb2
          port: 80
  tls:
    secretName: influxdb-certificate
