namespace: influxdb

helmCharts:
  - repo: https://helm.influxdata.com/
    name: influxdb2
    namespace: influxdb
    includeCRDs: true
    valuesFile: values.yml
    version: "2.1.1"
    releaseName: influxdb

resources:
  - namespace.yml
  - secrets.yml
  - certificate.yml
  - ingress.yml