---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-influxdb2-auth
  namespace: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: influxdb
        property: password
    - secretKey: admin-token
      remoteRef:
        key: influxdb
        property: admin-token