
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: access_key 
      remoteRef:
        key: minio
        property: access_key
    - secretKey: secret_key 
      remoteRef:
        key: minio
        property: secret_key
