---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: homelab
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1password-operator-token
            key: token
            namespace: external-secrets