binary_sensor:
  name: "Dark Outside"
  platform: "bayesian"
  prior: 0.6
  probability_threshold: 0.95
  observations:
    - platform: "state"
      entity_id: sun.sun
      prob_given_true: 0.9
      prob_given_false: 0.15
      to_state: "below_horizon"
    - platform: "state"
      entity_id: sun.sun
      prob_given_true: 0.25
      prob_given_false: 0.8
      to_state: "above_horizon"
    - platform: template
      prob_given_true: 0.96
      prob_given_false: 0.01
      value_template: >
        {{ states('sensor.balcony_light_sensor_illuminance_lux') | float <= states('input_number.dark_outside_lux_value') | float }}
    - platform: template
      value_template: >
        {{ states('weather.sumppari') == 'cloudy' and now().month is in [11,12,1,2] }}
      prob_given_true: 0.6
      prob_given_false: 0.3

