binary_sensor:
  name: "Dark Outside"
  platform: "bayesian"
  prior: 0.6
  probability_threshold: 0.95
  observations:
    - platform: "state"
      entity_id: sun.sun
      prob_given_true: 0.9
      prob_given_false: 0.1
      to_state: "below_horizon"
    - platform: template
      prob_given_true: 0.95
      prob_given_false: 0.05
      value_template: >
        {{ states('sensor.balcony_light_sensor_illuminance_lux') | float <= states('input_number.dark_outside_lux_value') | float }}
    - platform: template
      value_template: >
        {{ states('weather.sumppari') == 'cloudy' and states('sensor.season') == 'winter' }}
      prob_given_true: 0.5
      prob_given_false: 0.2

