binary_sensor:
  name: "Dark Outside"
  platform: "bayesian"
  prior: 0.6
  probability_threshold: 0.95
  observations:
    - platform: "state"
      entity_id: sun.sun
      prob_given_true: 0.8
      prob_given_false: 0.1
      to_state: "below_horizon"
    - platform: "numeric_state"
      entity_id: sensor.balcony_light_sensor_illuminance_lux
      prob_given_true: 0.85
      prob_given_false: 0.05
      below: 150
    - platform: template
      value_template: >
        {{ states('weather.sumppari') == 'cloudy' and states('sensor.season') == 'winter' }}
      prob_given_true: 0.6
      prob_given_false: 0.2

