sensor:
  - platform: history_stats
    name: Fridge Door Opened Today
    entity_id: binary_sensor.fridge_door_opened_sensor_contact
    state: "on"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
