mqtt:
  host: "{{ mqtt_broker_domain }}"
  port: 8883
  username: "{{ zigbee2mqtt_mqtt_username }}"
  password: "{{ zigbee2mqtt_mqtt_password }}"
  client_id: ble2mqtt
  protocol: mqtt

gateways:
  base_topic: ble2mqtt
  ruuvitag:
    allow_unknown: false
    devices:
      - name: Office Ruuvitag
        id: da21045d81a8
      - name: Fridge Ruuvitag
        id: f66b9906ee4e
  miflora:
    timeout: 120000
    devices:
      - name: Rahapuu
        id: c47c8d6e069c
      - name: Anopinkieli
        id: c47c8d6e07cf
