---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navilist-credentials
  namespace: navilist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: NAVIDROME_USER
      remoteRef:
        key: Navidrome
        property: username
    - secretKey: NAVIDROME_PASSWORD
      remoteRef:
        key: Navidrome
        property: password
    - secretKey: LASTFM_API_KEY
      remoteRef:
        key: last-fm-api-key
        property: api_key
    - secretKey: LASTFM_USERNAME
      remoteRef:
        key: last-fm-api-key
        property: username
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: lidarr-api-key
        property: password
