---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: route53-acme-dns01-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: route53-acme-dns01
        property: username
    - secretKey: accessKeySecret
      remoteRef:
        key: route53-acme-dns01
        property: password