docker_version: "latest"
docker_edition: 'ce'
iot_vlan_network: "192.168.30.0/24"
main_vlan_network: "192.168.10.0/24"
media_vlan_network: "192.168.50.0/24"
iot_untrusted_vlan_network: "192.168.40.0/24"
lan_network: "192.168.5.0/24"
remote_vpn_network: "10.0.10.0/24"
ansible_ssh_user: provisioner

pip_install_packages:
  - name: setuptools_rust
  - name: docker
  - name: docker-compose

lets_encrypt_user_email: "{{ vault_lets_encrypt_user_email }}"

route53_acme_access_key_id: "{{ vault_route53_acme_access_key_id }}"
route53_acme_secret_access_key: "{{ vault_route53_acme_secret_access_key }}"
route53_hosted_zone_id: "{{ vault_route53_hosted_zone_id }}"

home_assistant_mqtt_username: "{{ vault_home_assistant_mqtt_username }}"
home_assistant_mqtt_password: "{{ vault_home_assistant_mqtt_password }}"
zigbee2mqtt_mqtt_username: "{{ vault_zigbee2mqtt_mqtt_username }}"
zigbee2mqtt_mqtt_password: "{{ vault_zigbee2mqtt_mqtt_password }}"

mqtt_broker_domain: "{{ vault_mqtt_broker_domain }}"
mqtt_broker_port: 8883
mqtt_mosquitto_version: "2.0.22-openssl"
mqtt_broker_users:
  - { username: "{{ home_assistant_mqtt_username }}" , password: "{{ home_assistant_mqtt_password }}" }
  - { username: "{{ zigbee2mqtt_mqtt_username }}", password: "{{ zigbee2mqtt_mqtt_password }}" }

influxdb_domain: "{{ vault_influxdb_domain }}"
influxdb_admin_username: "{{ vault_influxdb_admin_username }}"
influxdb_admin_password: "{{ vault_influxdb_admin_password }}"
influxdb_admin_token: "{{ vault_influxdb_admin_token }}"
chronograf_domain: "{{ vault_chronograf_domain }}"
influxdb_home_assistant_username: "{{ vault_influxdb_home_assistant_username }}"
influxdb_home_assistant_password: "{{ vault_influxdb_home_assistant_password }}"

dropbox_access_token: "{{ vault_dropbox_access_token }}"
backup_password: "{{ vault_backup_password }}"

