- name: Ensure dependencies are present
  become: yes
  apt:
    name:
      - tar
      - openssl
      - curl
      - jq
      - systemd
    state: present
    update_cache: true

- name: Copy backup-to-dropbox.sh script
  become: yes
  copy:
    src: backup-to-dropbox.sh
    dest: /usr/local/bin/backup-to-dropbox.sh
    mode: 0755

- name: Copy systemd timer unit file for backup script
  become: yes
  template:
    src: backup-to-dropbox.service
    dest: /etc/systemd/system/backup-to-dropbox.service
    mode: 0644

- name: Enable backup-to-dropbox.service timer
  become: yes
  systemd:
    enabled: yes
    name: backup-to-dropbox.service
  notify: reload systemd daemons
