namespaceOverride: kube-system
providers:
  kubernetesIngress:
    publishedService:
      enabled: true

deployment:
  replicas: 2

service:
  externalTrafficPolicy: Local

env:
  - name: TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE
    value: "false"

globalArguments:
  - "--global.checknewversion"
