apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.10.50/32
    - 192.168.10.51/32
    - 192.168.10.52/32
    - 192.168.10.53/32