---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - https://github.com/metallb/metallb//config/native?ref=v0.13.12
  - ip-address-pool.yml
  - l2advertisement.yml
