#apiVersion: metallb.io/v1beta1
#kind: BGPAdvertisement
#metadata:
#  name: metallb-advertisement
#  namespace: metallb-system
#spec:
#  ipAddressPools:
#    - homelab-pool
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advetisement
  namespace: metallb-system