---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datasources
  namespace: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: datasources.yml
      remoteRef:
        key: grafana
        property: datasources.yml