---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: grafana
data:
  grafana.ini: |
    data = /var/lib/grafana/data
    logs = /var/lib/grafana/data/log
    plugins = /var/lib/grafana/data/plugins
    provisioning = /var/lib/grafana/conf/provisioning

    [server]
    domain = "grafana.lan.juusoleinonen.fi"
    enable_gzip= true

    # Redirect to correct domain if host header does not match domain
    # Prevents DNS rebinding attacks
    enforce_domain = true
    
    [security]
    admin_user = admin
    admin_email = "leinonen.juuso@gmail.com"
    cookie_secure = true

    [users]
    allow_sign_up = false
    default_language = en-US

    [log]
    mode = console
    level = info
    
    [analytics]
    reporting_enabled = false
