- name: Ensure Zigbee2MQTT docker network exists
  community.docker.docker_network:
    name: "{{ zigbee2mqtt_docker_network }}"
    ipam_config:
      - subnet: "{{ zigbee2mqtt_docker_network_subnet }}"
        gateway: "{{ zigbee2mqtt_docker_network_gateway }}"
    state: present
    appends: yes

- name: Ensure Zigbee2MQTT folder exists
  file:
    path: "{{ zigbee2mqtt_home_folder }}"
    state: directory
    owner: "{{ zigbee2mqtt_user }}"
    group: docker
    mode: 0755

- name: Ensure Zigbee2MQTT data folder exists
  file:
    path: "{{ zigbee2mqtt_home_folder }}/data"
    state: directory
    owner: "{{ zigbee2mqtt_user }}"
    group: docker
    mode: 0755

- name: Ensure Zigbee2MQTT configuration is present
  template:
    src: configuration.yaml
    dest: "{{ zigbee2mqtt_home_folder }}/data/configuration.yaml"
    group: docker
    mode: 0600
    owner: "{{ zigbee2mqtt_user }}"
  notify: restart zigbee2mqtt

- name: Ensure Zigbee2MQTT group configuration is present
  template:
    src: groups.yaml
    dest: "{{ zigbee2mqtt_home_folder }}/data/groups.yaml"
    group: docker
    mode: 0600
    owner: "{{ zigbee2mqtt_user }}"
  notify: restart zigbee2mqtt

- name: Ensure Zigbee2MQTT docker-compose file is present
  template:
    src: docker-compose.yml
    dest: "{{ zigbee2mqtt_home_folder }}/docker-compose.yml"
    group: docker
    mode: 0644
    owner: "{{ zigbee2mqtt_user }}"
  notify: restart zigbee2mqtt

- name: Ensure zigbee2mqtt is running
  community.docker.docker_compose:
    project_src: "{{ zigbee2mqtt_home_folder }}"
    state: present
