---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  commonName: argocd.lan.juusoleinonen.fi
  secretName: argocd-certificate
  dnsNames:
    - argocd.lan.juusoleinonen.fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.lan.juusoleinonen.fi`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: ipwhitelist
          namespace: kube-system
    - kind: Rule
      match: Host(`argocd.lan.juusoleinonen.fi`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
      middlewares:
        - name: ipwhitelist
          namespace: kube-system
  tls:
    secretName: argocd-certificate
