services:
  mosquitto:
    image: "eclipse-mosquitto:{{ mqtt_mosquitto_version }}"
    container_name: mosquitto
    user: "{{ mosquitto_user_id }}:{{ mosquitto_user_group_id }}"
    restart: unless-stopped
    volumes:
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
    labels:
      - traefik.enable=true
      - "traefik.tcp.services.mosquitto.loadbalancer.server.port={{ mqtt_broker_port }}"
      - traefik.tcp.routers.mosquitto.entrypoints=websecure
      - traefik.tcp.routers.mosquitto.service=mosquitto
      - "traefik.tcp.routers.mosquitto.rule=HostSNI(`{{ mqtt_broker_domain }}`)"
      - traefik.tcp.routers.mosquitto.tls=true
      - traefik.tcp.routers.mosquitto.tls.certresolver=lets-encrypt
    networks:
      "{{ mqtt_docker_network }}":
        ipv4_address: "{{ mosquitto_docker_ip }}"
networks:
  "{{ mqtt_docker_network }}":
    external: true
