services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: "koenkk/zigbee2mqtt:{{ zigbee2mqtt_version }}"
    ports:
      - 8080
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Helsinki
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2480755-if00:/dev/ttyACM0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`{{ zigbee2mqtt_domain }}`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=websecure"
      - "traefik.http.routers.zigbee2mqtt.tls.certresolver=lets-encrypt"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
    networks:
      - "{{ zigbee2mqtt_docker_network }}"
networks:
  "{{ zigbee2mqtt_docker_network }}":
    external: true
