homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  name: Sumppari
  temperature_unit: C
  time_zone: Europe/Helsinki
  unit_system: metric
  currency: EUR
  packages: !include_dir_named integrations
  external_url: !secret home_assistant_url
  internal_url: !secret home_assistant_url
default_config:
group: !include_dir_merge_named groups/

http:
  use_x_forwarded_for: true
  base_url: !secret home_assistant_url
  trusted_proxies:
    - !secret traefik_ip

sun:
