docker_compose_package_state: present
docker_install_compose: true
docker_compose_version: '1.29.2'
ansible_python_interpreter: /usr/bin/python3

###########################
# Security
###########################
ansible_ssh_user: provisioner
docker_users:
  - "provisioner"
  - "home_assistant"

allowed_network_sources:
  - "{{ iot_vlan_network }}"
  - "{{ main_vlan_network }}"
  - "{{ lan_network }}"
  - "{{ media_vlan_network }}"
  - "{{ iot_untrusted_vlan_network }}"
  - "{{ home_assistant_docker_network_subnet }}"
  - "{{ remote_vpn_network }}"

allowed_direct_access_to_home_assistant:
  - "{{ iot_vlan_network }}"

security_allow_http_traffic: true
security_allow_https_traffic: true

host_specific_firewall_rules: []

###########################
# Traefik
###########################
traefik_home_folder: "/home/{{ home_assistant_user }}/traefik"
traefik_user: "{{ home_assistant_user }}"
traefik_user_id: "{{ home_assistant_user_id }}"
traefik_user_group_id: "{{ home_assistant_user_group_id }}"

traefik_docker_network: "{{ home_assistant_docker_network }}"
traefik_docker_network_subnet: "{{ home_assistant_docker_network_subnet }}"
traefik_docker_network_gateway: "{{ home_assistant_docker_network_gateway }}"
traefik_docker_ip: "172.20.0.2"

traefik_version: "v3.1.2"
traefik_domain: "{{ vault_traefik_domain }}"

lets_encrypt_use_production: true

###########################
# Home assistant
###########################
philips_hue_bridge_ip: "{{ vault_philips_hue_bridge_ip }}"

home_longitude: "{{ vault_home_longitude }}"
home_latitude: "{{ vault_home_latitude }}"

netatmo_client_id: "{{ vault_netatmo_client_id }}"
netatmo_client_secret: "{{ vault_netatmo_client_secret }}"

influxdb_token: "{{ lookup('community.general.onepassword', 'influxdb', vault='homelab', field='home_assistant_token') }}"

home_assistant_user_password: "{{ vault_home_assistant_user_password }}"
home_assistant_user: home_assistant
home_assistant_user_id: 1024
home_assistant_user_group_id: 1004
home_assistant_home_folder: "/home/{{ home_assistant_user }}/home_assistant"
home_assistant_version: "2024.7"
home_assistant_docker_network: "home-assistant-network"
home_assistant_docker_network_subnet: "172.20.0.0/16"
home_assistant_docker_network_gateway: "172.20.0.1"
home_assistant_domain: "{{ vault_home_assistant_domain }}"
hacs_version: "1.34.0"

home_assistant_docker_ip: "172.20.0.3"

###########################
# MQTT
###########################
mqtt_docker_network_subnet: "{{ home_assistant_docker_network_subnet }}"
mqtt_docker_network: "{{ home_assistant_docker_network }}"
mqtt_docker_network_gateway: "{{ home_assistant_docker_network_gateway }}"
mosquitto_home_folder: "/home/{{ home_assistant_user }}/mosquitto"
mosquitto_user: "{{ home_assistant_user }}"
mosquitto_user_id: "{{ home_assistant_user_id }}"
mosquitto_user_group_id: "{{ home_assistant_user_group_id }}"
mosquitto_docker_ip: "172.20.0.4"
