---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transmission-ovpn-config
  namespace: transmission
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: se.opvn.com.ovpn
      remoteRef:
        key: ovpn_config
        property: se.ovpn.com.ovpn
