---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ovpn-credentials
  namespace: transmission
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USERNAME
      remoteRef:
        key: ovpn-credentials
        property: username
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: ovpn-credentials
        property: password
