services:
  traefik:
    container_name: traefik
    image: "traefik:{{ traefik_version }}"
    restart: unless-stopped
    networks:
      "{{ traefik_docker_network }}":
        ipv4_address: "{{ traefik_docker_ip }}"
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - "{{ traefik_home_folder }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ traefik_home_folder }}/acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_domain }}`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.service: "api@internal"
    environment:
      AWS_REGION: "eu-north-1"
      AWS_ACCESS_KEY_ID: "{{ route53_acme_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ route53_acme_secret_access_key }}"
      AWS_HOSTED_ZONE_ID: "{{ route53_hosted_zone_id }}"
networks:
  "{{ traefik_docker_network }}":
    external: true
