---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mimir-minio-credentials
  namespace: grafana-mimir
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: mimir
        property: minio_access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: mimir
        property: minio_secret_key