---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-mimir-pvc
  namespace: grafana-mimir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
