---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-mimir-pvc
  namespace: grafana-mimir
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
