---
- hosts: all
  roles:
    - { name: base_security, become: true }
    - { name: geerlingguy.pip, become: true }

- hosts: home_assistant
  roles:
    - { name: geerlingguy.docker}
    - { name: traefik, become: true }
    - { name: home_assistant, become: true }
    - { name: mosquitto, become: true }


- hosts: mqtt_gateway
  roles:
    - { name: geerlingguy.docker_arm, become: true }
    - { name: traefik, become: true }
    - { name: zigbee2mqtt, become: true }
    - { name: ble2mqtt, become: true }


