---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: last-fm-api-key
  namespace: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab
  target:
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: last-fm-api-key
        property: api_key
    - secretKey: shared_secret
      remoteRef:
        key: last-fm-api-key
        property: shared_secret
