---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-certificate
  namespace: unifi
spec:
  commonName: unifi.lan.juusoleinonen.fi
  secretName: unifi-certificate
  dnsNames:
    - unifi.lan.juusoleinonen.fi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer